# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my-first-package',
                'doc_host': 'https://Manjunath-Yelipeta.github.io',
                'git_url': 'https://github.com/Manjunath-Yelipeta/my-first-package',
                'lib_path': 'my_first_package'},
  'syms': {'my_first_package.core': {'my_first_package.core.foo': ('core.html#foo', 'my_first_package/core.py')}}}
